/*
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * HLRCallback
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-05T22:22:19.233-07:00")
public class HLRCallback {
  @SerializedName("id")
  private String id = null;

  @SerializedName("msisdn")
  private Long msisdn = null;

  /**
   * Short status code of the response
   */
  public enum StatusEnum {
    @SerializedName("valid")
    VALID("valid"),
    
    @SerializedName("invalid")
    INVALID("invalid"),
    
    @SerializedName("unknown")
    UNKNOWN("unknown");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("operator")
  private String operator = null;

  @SerializedName("mccmnc")
  private Integer mccmnc = null;

  /**
   * If the response code is temporary or permenant
   */
  public enum DurationEnum {
    @SerializedName("perm")
    PERM("perm"),
    
    @SerializedName("temp")
    TEMP("temp");

    private String value;

    DurationEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("duration")
  private DurationEnum duration = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("extended")
  private String extended = null;

  @SerializedName("cost")
  private Float cost = null;

  public HLRCallback id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID for response
   * @return id
  **/
  @ApiModelProperty(example = "13Cy205d697R", value = "Unique ID for response")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public HLRCallback msisdn(Long msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * The MSISDN of the number queried
   * @return msisdn
  **/
  @ApiModelProperty(example = "61412345678", value = "The MSISDN of the number queried")
  public Long getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(Long msisdn) {
    this.msisdn = msisdn;
  }

  public HLRCallback status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Short status code of the response
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Short status code of the response")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public HLRCallback country(String country) {
    this.country = country;
    return this;
  }

   /**
   * ISO 3166-2 country code
   * @return country
  **/
  @ApiModelProperty(example = "AU", value = "ISO 3166-2 country code")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public HLRCallback operator(String operator) {
    this.operator = operator;
    return this;
  }

   /**
   * The operator attached to the MSISDN
   * @return operator
  **/
  @ApiModelProperty(example = "(AUSTRALIA)OPTUS", value = "The operator attached to the MSISDN")
  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }

  public HLRCallback mccmnc(Integer mccmnc) {
    this.mccmnc = mccmnc;
    return this;
  }

   /**
   * MCC and MNC of MSDISDN
   * @return mccmnc
  **/
  @ApiModelProperty(example = "50503", value = "MCC and MNC of MSDISDN")
  public Integer getMccmnc() {
    return mccmnc;
  }

  public void setMccmnc(Integer mccmnc) {
    this.mccmnc = mccmnc;
  }

  public HLRCallback duration(DurationEnum duration) {
    this.duration = duration;
    return this;
  }

   /**
   * If the response code is temporary or permenant
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "If the response code is temporary or permenant")
  public DurationEnum getDuration() {
    return duration;
  }

  public void setDuration(DurationEnum duration) {
    this.duration = duration;
  }

  public HLRCallback message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Full status code of the response
   * @return message
  **/
  @ApiModelProperty(example = "subscriber preset", value = "Full status code of the response")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public HLRCallback extended(String extended) {
    this.extended = extended;
    return this;
  }

   /**
   * Extended explanation of the status code
   * @return extended
  **/
  @ApiModelProperty(example = "Subscriber present", value = "Extended explanation of the status code")
  public String getExtended() {
    return extended;
  }

  public void setExtended(String extended) {
    this.extended = extended;
  }

  public HLRCallback cost(Float cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Cost of the response
   * @return cost
  **/
  @ApiModelProperty(example = "0.01", value = "Cost of the response")
  public Float getCost() {
    return cost;
  }

  public void setCost(Float cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLRCallback hlRCallback = (HLRCallback) o;
    return Objects.equals(this.id, hlRCallback.id) &&
        Objects.equals(this.msisdn, hlRCallback.msisdn) &&
        Objects.equals(this.status, hlRCallback.status) &&
        Objects.equals(this.country, hlRCallback.country) &&
        Objects.equals(this.operator, hlRCallback.operator) &&
        Objects.equals(this.mccmnc, hlRCallback.mccmnc) &&
        Objects.equals(this.duration, hlRCallback.duration) &&
        Objects.equals(this.message, hlRCallback.message) &&
        Objects.equals(this.extended, hlRCallback.extended) &&
        Objects.equals(this.cost, hlRCallback.cost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, msisdn, status, country, operator, mccmnc, duration, message, extended, cost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLRCallback {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    mccmnc: ").append(toIndentedString(mccmnc)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    extended: ").append(toIndentedString(extended)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

