/*
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * HLRResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-04T01:25:59.406-07:00")
public class HLRResult {
  @SerializedName("status")
  private String status = null;

  @SerializedName("success")
  private List<Long> success = new ArrayList<Long>();

  @SerializedName("failure")
  private List<Long> failure = new ArrayList<Long>();

  @SerializedName("cost")
  private Float cost = null;

  @SerializedName("callback")
  private String callback = null;

  public HLRResult status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "success", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public HLRResult success(List<Long> success) {
    this.success = success;
    return this;
  }

  public HLRResult addSuccessItem(Long successItem) {
    this.success.add(successItem);
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getSuccess() {
    return success;
  }

  public void setSuccess(List<Long> success) {
    this.success = success;
  }

  public HLRResult failure(List<Long> failure) {
    this.failure = failure;
    return this;
  }

  public HLRResult addFailureItem(Long failureItem) {
    this.failure.add(failureItem);
    return this;
  }

   /**
   * Get failure
   * @return failure
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Long> getFailure() {
    return failure;
  }

  public void setFailure(List<Long> failure) {
    this.failure = failure;
  }

  public HLRResult cost(Float cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Cost of the response
   * @return cost
  **/
  @ApiModelProperty(example = "0.01", value = "Cost of the response")
  public Float getCost() {
    return cost;
  }

  public void setCost(Float cost) {
    this.cost = cost;
  }

  public HLRResult callback(String callback) {
    this.callback = callback;
    return this;
  }

   /**
   * Callback URL provided
   * @return callback
  **/
  @ApiModelProperty(example = "http://www.example.com/hlr-callback.php", value = "Callback URL provided")
  public String getCallback() {
    return callback;
  }

  public void setCallback(String callback) {
    this.callback = callback;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HLRResult hlRResult = (HLRResult) o;
    return Objects.equals(this.status, hlRResult.status) &&
        Objects.equals(this.success, hlRResult.success) &&
        Objects.equals(this.failure, hlRResult.failure) &&
        Objects.equals(this.cost, hlRResult.cost) &&
        Objects.equals(this.callback, hlRResult.callback);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, success, failure, cost, callback);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HLRResult {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    callback: ").append(toIndentedString(callback)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

