/*
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SMSResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-05T22:22:19.233-07:00")
public class SMSResult {
  @SerializedName("id")
  private String id = null;

  @SerializedName("success")
  private Integer success = null;

  @SerializedName("cost")
  private Float cost = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("failure")
  private List<String> failure = new ArrayList<String>();

  public SMSResult id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique ID for response
   * @return id
  **/
  @ApiModelProperty(example = "13Cy205d697R", value = "Unique ID for response")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SMSResult success(Integer success) {
    this.success = success;
    return this;
  }

   /**
   * Count of queued SMS
   * @return success
  **/
  @ApiModelProperty(example = "3", value = "Count of queued SMS")
  public Integer getSuccess() {
    return success;
  }

  public void setSuccess(Integer success) {
    this.success = success;
  }

  public SMSResult cost(Float cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Cost of the SMS
   * @return cost
  **/
  @ApiModelProperty(example = "0.079", value = "Cost of the SMS")
  public Float getCost() {
    return cost;
  }

  public void setCost(Float cost) {
    this.cost = cost;
  }

  public SMSResult count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Total count of SMS queued
   * @return count
  **/
  @ApiModelProperty(example = "5", value = "Total count of SMS queued")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public SMSResult failure(List<String> failure) {
    this.failure = failure;
    return this;
  }

  public SMSResult addFailureItem(String failureItem) {
    this.failure.add(failureItem);
    return this;
  }

   /**
   * List of failed numbers
   * @return failure
  **/
  @ApiModelProperty(example = "null", value = "List of failed numbers")
  public List<String> getFailure() {
    return failure;
  }

  public void setFailure(List<String> failure) {
    this.failure = failure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SMSResult smSResult = (SMSResult) o;
    return Objects.equals(this.id, smSResult.id) &&
        Objects.equals(this.success, smSResult.success) &&
        Objects.equals(this.cost, smSResult.cost) &&
        Objects.equals(this.count, smSResult.count) &&
        Objects.equals(this.failure, smSResult.failure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, success, cost, count, failure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SMSResult {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

